# Generated by Django 4.2.10 on 2024-02-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pick',
        ),
    ]
