# Generated by Django 4.2.10 on 2024-02-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_delete_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_fields', models.ManyToManyField(related_name='picks', to='garden.apifield')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picks', models.ManyToManyField(related_name='packages', to='garden.pick')),
            ],
        ),
    ]
