# Generated by Django 4.2.10 on 2024-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_apifield_pick_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='full_query_command',
            field=models.TextField(default='', help_text='The full command to fetch data, including authentication and any flags.'),
        ),
    ]
