# Generated by Django 4.2.10 on 2024-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_plant_full_query_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='api_auth_key',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='api_auth_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='api_method',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='api_param_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='api_param_value',
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.IntegerField(default=0, help_text='Current status of the plant (0 for inactive, 1 for active).'),
        ),
    ]
