# Generated by Django 4.2.10 on 2024-02-18 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_remove_plant_api_auth_key_remove_plant_api_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last status change.'),
        ),
    ]
